spring:
  datasource:
    url: jdbc:postgresql://${env.DB_HOST}:${env.DB_PORT}/${env.DB_NAME}
    username: ${env.DB_USER}
    password: ${env.DB_PASS}
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  mail:
    host: ${env.MAIL_HOST}
    port: ${env.MAIL_PORT}
    username: ${env.MAIL_USER}
    password: ${env.MAIL_PASS}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


